export const EVENTS = {
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_STATUS_CHANGED: "PROJECT_STATUS_CHANGED",
  PROJECT_LIKED: "PROJECT_LIKED",
  USER_FOLLOWED: "USER_FOLLOWED",
};

export default EVENTS;
