export const USER_ROLES = {
  STUDENT: 'STUDENT',
  RECRUITER: 'RECRUITER',
  ADMIN: 'ADMIN',
};

export const PROJECT_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  HIDDEN: 'HIDDEN',
};

export const PROJECT_CATEGORIES = [
  'WEB DEVELOPMENT',
  'MOBILE DEVELOPMENT',
  'DESKTOP APPLICATION',
  'ARTIFICIAL INTELLIGENCE',
  'MACHINE LEARNING',
  'INTERNET OF THINGS',
  'CYBER SECURITY',
  'CLOUD COMPUTING',
  'DATA SCIENCE',
  'GAME DEVELOPMENT',
  'BLOCKCHAIN',
  'OTHER',
];

export const BASE_URL = 'http://localhost:3000/api';
