export const NOTIFICATION_TYPES = Object.freeze({
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_APPROVED: "PROJECT_APPROVED",
  PROJECT_REJECTED: "PROJECT_REJECTED",
  PROJECT_HIDDEN: "PROJECT_HIDDEN",
  PROJECT_LIKED: "PROJECT_LIKED",
  USER_FOLLOWED: "USER_FOLLOWED",
});